version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      - POSTGRES_DB=django_visitka
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - django-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@visitka.com
      - PGADMIN_DEFAULT_PASSWORD=adminpassword
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - db
    networks:
      - django-network

  redis:
    image: redis:7-alpine
    container_name: redis_cache
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - django-network

  web:
    build: .
    container_name: django_web
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - static_volume:/app/static
      - media_volume:/app/media
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:secretpassword@db:5432/django_visitka
      - POSTGRES_DB=django_visitka
      - POSTGRES_USER=django_user
      - POSTGRES_PASSWORD=secretpassword
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    restart: unless-stopped
    networks:
      - django-network

  celery:
    build: .
    container_name: celery_worker
    volumes:
      - ./app:/app
    command: celery -A visitka worker --loglevel=info
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:secretpassword@db:5432/django_visitka
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web
    restart: unless-stopped
    networks:
      - django-network

  celery-beat:
    build: .
    container_name: celery_beat
    volumes:
      - ./app:/app
    command: celery -A visitka beat --loglevel=info
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:secretpassword@db:5432/django_visitka
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web
    restart: unless-stopped
    networks:
      - django-network

  flower:
    build: .
    container_name: flower_monitor
    ports:
      - "5555:5555"
    volumes:
      - ./app:/app
    command: celery -A visitka flower --port=5555 --broker=redis://redis:6379/0
    environment:
      - DEBUG=True
      - DATABASE_URL=postgres://django_user:secretpassword@db:5432/django_visitka
      - REDIS_URL=redis://redis:6379/0
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
      - web
      - celery
    restart: unless-stopped
    networks:
      - django-network

networks:
  django-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
